/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ncsa_im2learn_core_geo_projection_MRTInterface */

#ifndef _Included_ncsa_im2learn_core_geo_projection_MRTInterface
#define _Included_ncsa_im2learn_core_geo_projection_MRTInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    geo2coord
 * Signature: (IDD[D)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_geo2coord
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdoubleArray);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    coord2geo
 * Signature: (IDD[D)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_coord2geo
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdoubleArray);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    utmint
 * Signature: (IDDDJ)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_utmint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jlong);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    stplnint
 * Signature: (IJJLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_stplnint
  (JNIEnv *, jclass, jint, jlong, jlong, jstring, jstring);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    alberint
 * Signature: (IDDDDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_alberint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    lamccint
 * Signature: (IDDDDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_lamccint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    merint
 * Signature: (IDDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_merint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    psint
 * Signature: (IDDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_psint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    polyint
 * Signature: (IDDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_polyint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    eqconint
 * Signature: (IDDDDDDDDJ)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_eqconint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jlong);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    tmint
 * Signature: (IDDDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_tmint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    sterint
 * Signature: (IDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_sterint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    lamazint
 * Signature: (IDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_lamazint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    azimint
 * Signature: (IDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_azimint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    gnomint
 * Signature: (IDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_gnomint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    orthint
 * Signature: (IDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_orthint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    gvnspint
 * Signature: (IDDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_gvnspint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    sinint
 * Signature: (IDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_sinint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    equiint
 * Signature: (IDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_equiint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    millint
 * Signature: (IDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_millint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    vandgint
 * Signature: (IDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_vandgint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    omerint
 * Signature: (IDDDDDDDDDDDDJ)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_omerint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jlong);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    robint
 * Signature: (IDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_robint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    somint
 * Signature: (IDDJJDDDDDJJ)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_somint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jlong, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jlong, jlong);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    alconint
 * Signature: (IDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_alconint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    goodint
 * Signature: (ID)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_goodint
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    molwint
 * Signature: (IDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_molwint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    imolwint
 * Signature: (ID)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_imolwint
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    hamint
 * Signature: (IDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_hamint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    wivint
 * Signature: (IDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_wivint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    wviiint
 * Signature: (IDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_wviiint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    obleqint
 * Signature: (IDDDDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_obleqint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     ncsa_im2learn_core_geo_projection_MRTInterface
 * Method:    isinusint
 * Signature: (IDDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_ncsa_im2learn_core_geo_projection_MRTInterface_isinusint
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
