package edu.illinois.ncsa.isda.imagetools.core.geo;

import java.util.HashMap;

/**
 * http://www.colorado.edu/geography/gcraft/notes/datum/edlist.html
 * 
 * @author kooper
 * 
 */
public class Datum {
	/** List to map from string representation of datum, to datum object. */
	static private HashMap<String, Datum>	map	= new HashMap<String, Datum>();

	/**
	 * Given the name of a datum, return the datum. This will return null if no
	 * datum was found with the exact name.
	 * 
	 * @param name
	 *            the name of the datum to look for.
	 * @return the datum if found, or null if no datum was found with this name.
	 */
	static public Datum getDatum(String name) {
		String lname = name.toLowerCase().replace("_", " ");
		if (lname.startsWith("d ")) {
			lname = lname.substring(2);
		}
		return map.get(lname);
	}

	// added to support at least one sphere model
	// this datum is supported by Arc GIS
	// see
	// http://edndoc.esri.com/arcobjects/9.2/CPP_VB6_VBA_VCPP_Doc/COM_Samples_Docs/Geometry/6f349d0e-895d-42ae-96d4-f6837a161858.htm
	// http://publib.boulder.ibm.com/infocenter/idshelp/v10/index.jsp?topic=/com.ibm.spatial.doc/spat262.htm
	static public final Datum	Authalic_Sphere;

	// Autogenerated 208 datums.
	static public final Datum	Adindan_Burkina_Faso;
	static public final Datum	Adindan_Cameroon;
	static public final Datum	Adindan_Ethiopia;
	static public final Datum	Adindan_Mali;
	static public final Datum	Adindan_Mean;
	static public final Datum	Adindan_Senegal;
	static public final Datum	Adindan_Sudan;
	static public final Datum	Afgooye;
	static public final Datum	Ain_el_Abd_1970_Bahrain;
	static public final Datum	Ain_el_Abd_1970_Saudi_Arabia;
	static public final Datum	American_Samoa_1962;
	static public final Datum	Anna_1_Astro_1965;
	static public final Datum	Antigua_Island_Astro_1943;
	static public final Datum	Arc_1950_Botswana;
	static public final Datum	Arc_1950_Burundi;
	static public final Datum	Arc_1950_Lesotho;
	static public final Datum	Arc_1950_Malawi;
	static public final Datum	Arc_1950_Mean;
	static public final Datum	Arc_1950_Swaziland;
	static public final Datum	Arc_1950_Zaire;
	static public final Datum	Arc_1950_Zambia;
	static public final Datum	Arc_1950_Zimbabwe;
	static public final Datum	Arc_1960_Mean;
	static public final Datum	Ascension_Island_1958;
	static public final Datum	Astro_Beacon_E_1945;
	static public final Datum	Astro_DOS_714;
	static public final Datum	Astro_Tern_Island_1961;
	static public final Datum	Astronomical_Station_1952;
	static public final Datum	Australian_Geodetic_1966;
	static public final Datum	Australian_Geodetic_1984;
	static public final Datum	Ayabelle_Lighthouse;
	static public final Datum	Bellevue;
	static public final Datum	Bermuda_1957;
	static public final Datum	Bissau;
	static public final Datum	Bogota_Observatory;
	static public final Datum	Bukit_Rimpah;
	static public final Datum	Camp_Area_Astro;
	static public final Datum	Campo_Inchauspe;
	static public final Datum	Canton_Astro_1966;
	static public final Datum	Cape;
	static public final Datum	Cape_Canaveral;
	static public final Datum	Carthage;
	static public final Datum	Chatham_Island_Astro_1971;
	static public final Datum	Chua_Astro;
	static public final Datum	Corrego_Alegre;
	static public final Datum	DOS_1968;
	static public final Datum	Dabola;
	static public final Datum	Deception_Island;
	static public final Datum	Djakarta_Batavia;
	static public final Datum	Easter_Island_1967;
	static public final Datum	European_1950_Cyprus;
	static public final Datum	European_1950_Egypt;
	static public final Datum	European_1950_England;
	static public final Datum	European_1950_England_Channel;
	static public final Datum	European_1950_Finland_Norway;
	static public final Datum	European_1950_Greece;
	static public final Datum	European_1950_Iran;
	static public final Datum	European_1950_Italy_Sardinia;
	static public final Datum	European_1950_Italy_Sicily;
	static public final Datum	European_1950_Malta;
	static public final Datum	European_1950_Mean_Europe;
	static public final Datum	European_1950_Middle_East;
	static public final Datum	European_1950_North_West_Europe;
	static public final Datum	European_1950_Protugal_Spain;
	static public final Datum	European_1950_Tunisia;
	static public final Datum	European_1979_Mean;
	static public final Datum	Fort_Thomas_1955;
	static public final Datum	GUX_1_Astro;
	static public final Datum	Gan_1970;
	static public final Datum	Geodetic_Datum_1949;
	static public final Datum	Guam_1963;
	static public final Datum	Gunung_Segara;
	static public final Datum	Herat_North;
	static public final Datum	Hjorsey_1955;
	static public final Datum	Hong_Kong_1963;
	static public final Datum	Hu_Tzu_Shan;
	static public final Datum	ISTS_061_Astro_1968;
	static public final Datum	ISTS_073_Astro_1969;
	static public final Datum	Indian_Bangladesh;
	static public final Datum	Indian_India_Nepal;
	static public final Datum	Indian_Pakistan;
	static public final Datum	Indian_1954;
	static public final Datum	Indian_1960_Vietnam_Cons_Son;
	static public final Datum	Indian_1960_Vietnam_Near_16_N;
	static public final Datum	Indian_1975;
	static public final Datum	Indonesian_1974;
	static public final Datum	Ireland_1965;
	static public final Datum	Johnston_Island_1961;
	static public final Datum	Kandawala;
	static public final Datum	Kerguelen_Island_1949;
	static public final Datum	Kertau_1948;
	static public final Datum	Kusaie_Astro_1951;
	static public final Datum	L_C_5_Astro_1961;
	static public final Datum	Leigon;
	static public final Datum	Liberia_1964;
	static public final Datum	Luzon_Philippines;
	static public final Datum	Luzon_Philippines_Mindanao;
	static public final Datum	MPoraloko;
	static public final Datum	Mahe_1971;
	static public final Datum	Massawa;
	static public final Datum	Merchich;
	static public final Datum	Midway_Astro_1961;
	static public final Datum	Minna_Cameroon;
	static public final Datum	Minna_Nigeria;
	static public final Datum	Montserrat_Island_Astro_1958;
	static public final Datum	NTF_Nouvelle_Triangulation_de_France;
	static public final Datum	Nahrwan_Oman;
	static public final Datum	Nahrwan_Saudi_Arabia;
	static public final Datum	Nahrwan_United_Arab_Emirates;
	static public final Datum	Naparima_BWI;
	static public final Datum	North_American_1927_Alaska;
	static public final Datum	North_American_1927_Alaska_Aleutian_East;
	static public final Datum	North_American_1927_Alaska_Aleutian_West;
	static public final Datum	North_American_1927_Bahamas;
	static public final Datum	North_American_1927_Bahamas_San_Salvador;
	static public final Datum	North_American_1927_Canada;
	static public final Datum	North_American_1927_Canada_East;
	static public final Datum	North_American_1927_Canada_Middle;
	static public final Datum	North_American_1927_Canada_North;
	static public final Datum	North_American_1927_Canada_West;
	static public final Datum	North_American_1927_Canada_Yukon;
	static public final Datum	North_American_1927_Canal_Zone;
	static public final Datum	North_American_1927_Caribean;
	static public final Datum	North_American_1927_Central_America;
	static public final Datum	North_American_1927_Conus;
	static public final Datum	North_American_1927_Conus_East;
	static public final Datum	North_American_1927_Conus_West;
	static public final Datum	North_American_1927_Cuba;
	static public final Datum	North_American_1927_Greenland;
	static public final Datum	North_American_1927_Mexico;
	static public final Datum	North_American_1983_Alaska;
	static public final Datum	North_American_1983_Alaska_Aleutian;
	static public final Datum	North_American_1983_Canada;
	static public final Datum	North_American_1983_Central_America;
	static public final Datum	North_American_1983_Conus;
	static public final Datum	North_American_1983_Hawaii;
	static public final Datum	North_American_1983_Mexico;
	static public final Datum	North_Sahara_1959;
	static public final Datum	Observatorio_Meteorologico_1939;
	static public final Datum	Old_Egyptian_1907;
	static public final Datum	Old_Hawaiian_Hawaii;
	static public final Datum	Old_Hawaiian_Kauai;
	static public final Datum	Old_Hawaiian_Maui;
	static public final Datum	Old_Hawaiian_Mean;
	static public final Datum	Old_Hawaiian_Oahu;
	static public final Datum	Oman;
	static public final Datum	Ordnance_Survey_Great_Britain_1936_England;
	static public final Datum	Ordnance_Survey_Great_Britain_1936_England_Wales;
	static public final Datum	Ordnance_Survey_Great_Britain_1936_Mean;
	static public final Datum	Ordnance_Survey_Great_Britain_1936_Scotland;
	static public final Datum	Ordnance_Survey_Great_Britain_1936_Wales;
	static public final Datum	Pico_de_las_Nieves;
	static public final Datum	Pitcairn_Astro_1967;
	static public final Datum	Point_58;
	static public final Datum	Pointe_Noire_1948;
	static public final Datum	Porto_Santo_1936;
	static public final Datum	Provisional_South_American_1956_Bolivia;
	static public final Datum	Provisional_South_American_1956_Chile_North;
	static public final Datum	Provisional_South_American_1956_Chile_South;
	static public final Datum	Provisional_South_American_1956_Colombia;
	static public final Datum	Provisional_South_American_1956_Ecuador;
	static public final Datum	Provisional_South_American_1956_Guyana;
	static public final Datum	Provisional_South_American_1956_Mean;
	static public final Datum	Provisional_South_American_1956_Peru;
	static public final Datum	Provisional_South_American_1956_Venezuela;
	static public final Datum	Provisional_South_Chilean_1963;
	static public final Datum	Puerto_Rico;
	static public final Datum	Pulkovo_1942;
	static public final Datum	Qatar_National;
	static public final Datum	Qornoq;
	static public final Datum	Reunion;
	static public final Datum	Rijks_Driehoeksmeting;
	static public final Datum	Rome_1940;
	static public final Datum	S_42_Pulkovo_1942;
	static public final Datum	S_JTSK;
	static public final Datum	Santo_DOS_1965;
	static public final Datum	Sao_Braz;
	static public final Datum	Sapper_Hill_1943;
	static public final Datum	Schwarzeck;
	static public final Datum	Selvagem_Grande_1938;
	static public final Datum	South_American_1969_Argentina;
	static public final Datum	South_American_1969_Bolivia;
	static public final Datum	South_American_1969_Brazil;
	static public final Datum	South_American_1969_Chile;
	static public final Datum	South_American_1969_Colombia;
	static public final Datum	South_American_1969_Ecuador;
	static public final Datum	South_American_1969_Ecuador_Baltra;
	static public final Datum	South_American_1969_Guyana;
	static public final Datum	South_American_1969_Mean;
	static public final Datum	South_American_1969_Paraguay;
	static public final Datum	South_American_1969_Peru;
	static public final Datum	South_American_1969_Trinidad_and_Tobago;
	static public final Datum	South_American_1969_Venezuala;
	static public final Datum	South_Asia;
	static public final Datum	Tananarive_Observatory_1925;
	static public final Datum	Timbalai_1948;
	static public final Datum	Tokyo_Japan;
	static public final Datum	Tokyo_Mean;
	static public final Datum	Tokyo_Okinawa;
	static public final Datum	Tokyo_South_Korea;
	static public final Datum	Tristan_Astro_1968;
	static public final Datum	Viti_Levu_1916;
	static public final Datum	Voirol_1960;
	static public final Datum	WGS_1984;
	static public final Datum	Wake_Island_Astro_1952;
	static public final Datum	Wake_Eniwetok_1960;
	static public final Datum	Yacare;
	static public final Datum	Zanderij;

	static {
		// the numbers (0,0,0) are only estimated for Authalic_Sphere
		// based on ArcGIS PRJ file example
		// test PRJ file from http://edndoc.esri.com/arcims/9.2/elements/pcs.htm
		// PROJCS["US_National_Atlas_Equal_Area",GEOGCS["GCS_Sphere_Clarke_1866_Authalic",DATUM["D_Sphere_Clarke_1866_Authalic",SPHEROID["Sphere_Clarke_1866_Authalic",6370997.0,0.0]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Azimuthal_Equal_Area"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-100.0],PARAMETER["Latitude_Of_Origin",45.0],UNIT["Meter",1.0]]
		Authalic_Sphere = new Datum("Authalic Sphere", "North America", Ellipsoid.Clarke_1866, 0, 0, 0);
		map.put("authalic sphere", Authalic_Sphere);
		Adindan_Burkina_Faso = new Datum("Adindan Burkina Faso", "Burkina Faso", Ellipsoid.Clarke_1880, -118, -14, 218);
		map.put("adindan burkina faso", Adindan_Burkina_Faso);
		Adindan_Cameroon = new Datum("Adindan Cameroon", "Cameroon", Ellipsoid.Clarke_1880, -134, -2, 210);
		map.put("adindan cameroon", Adindan_Cameroon);
		Adindan_Ethiopia = new Datum("Adindan Ethiopia", "Ethiopia", Ellipsoid.Clarke_1880, -165, -11, 206);
		map.put("adindan ethiopia", Adindan_Ethiopia);
		Adindan_Mali = new Datum("Adindan Mali", "Mali", Ellipsoid.Clarke_1880, -123, -20, 220);
		map.put("adindan mali", Adindan_Mali);
		Adindan_Mean = new Datum("Adindan Mean", "Mean for Ethiopia, Mali, Senegal, Sudan", Ellipsoid.Clarke_1880,
				-162, -12, 206);
		map.put("adindan mean", Adindan_Mean);
		Adindan_Senegal = new Datum("Adindan Senegal", "Senegal", Ellipsoid.Clarke_1880, -128, -18, 224);
		map.put("adindan senegal", Adindan_Senegal);
		Adindan_Sudan = new Datum("Adindan Sudan", "Sudan", Ellipsoid.Clarke_1880, -161, -14, 205);
		map.put("adindan sudan", Adindan_Sudan);
		Afgooye = new Datum("Afgooye", "Somalia", Ellipsoid.Krassovsky_1940, -43, -163, 45);
		map.put("afgooye", Afgooye);
		Ain_el_Abd_1970_Bahrain = new Datum("Ain el Abd 1970 Bahrain", "Bahrain", Ellipsoid.International_1924, -150,
				-250, -1);
		map.put("ain el abd 1970 bahrain", Ain_el_Abd_1970_Bahrain);
		Ain_el_Abd_1970_Saudi_Arabia = new Datum("Ain el Abd 1970 Saudi Arabia", "Saudi Arabia",
				Ellipsoid.International_1924, -143, -236, 7);
		map.put("ain el abd 1970 saudi arabia", Ain_el_Abd_1970_Saudi_Arabia);
		American_Samoa_1962 = new Datum("American Samoa 1962", "American Samoa Islands", Ellipsoid.Clarke_1866, -115,
				118, 426);
		map.put("american samoa 1962", American_Samoa_1962);
		Anna_1_Astro_1965 = new Datum("Anna 1 Astro 1965", "Cocos Islands", Ellipsoid.Australian_National, -491, -22,
				435);
		map.put("anna 1 astro 1965", Anna_1_Astro_1965);
		Antigua_Island_Astro_1943 = new Datum("Antigua Island Astro 1943", "Antigua (Leeward Islands)",
				Ellipsoid.Clarke_1880, -270, 13, 62);
		map.put("antigua island astro 1943", Antigua_Island_Astro_1943);
		Arc_1950_Botswana = new Datum("Arc 1950 Botswana", "Botswana", Ellipsoid.Clarke_1880, -138, -105, -289);
		map.put("arc 1950 botswana", Arc_1950_Botswana);
		Arc_1950_Burundi = new Datum("Arc 1950 Burundi", "Burundi", Ellipsoid.Clarke_1880, -153, -5, -292);
		map.put("arc 1950 burundi", Arc_1950_Burundi);
		Arc_1950_Lesotho = new Datum("Arc 1950 Lesotho", "Lesotho", Ellipsoid.Clarke_1880, -125, -108, -295);
		map.put("arc 1950 lesotho", Arc_1950_Lesotho);
		Arc_1950_Malawi = new Datum("Arc 1950 Malawi", "Malawi", Ellipsoid.Clarke_1880, -161, -73, -317);
		map.put("arc 1950 malawi", Arc_1950_Malawi);
		Arc_1950_Mean = new Datum("Arc 1950 Mean",
				"Mean for Botswana, Lesotho, Malawi, Swaziland, Zaire, Zambia, Zimbabwe", Ellipsoid.Clarke_1880, -143,
				-90, -294);
		map.put("arc 1950 mean", Arc_1950_Mean);
		Arc_1950_Swaziland = new Datum("Arc 1950 Swaziland", "Swaziland", Ellipsoid.Clarke_1880, -134, -105, -295);
		map.put("arc 1950 swaziland", Arc_1950_Swaziland);
		Arc_1950_Zaire = new Datum("Arc 1950 Zaire", "Zaire", Ellipsoid.Clarke_1880, -169, -19, -278);
		map.put("arc 1950 zaire", Arc_1950_Zaire);
		Arc_1950_Zambia = new Datum("Arc 1950 Zambia", "Zambia", Ellipsoid.Clarke_1880, -147, -74, -283);
		map.put("arc 1950 zambia", Arc_1950_Zambia);
		Arc_1950_Zimbabwe = new Datum("Arc 1950 Zimbabwe", "Zimbabwe", Ellipsoid.Clarke_1880, -142, -96, -293);
		map.put("arc 1950 zimbabwe", Arc_1950_Zimbabwe);
		Arc_1960_Mean = new Datum("Arc 1960 Mean", "Mean for Kenya, Tanzania", Ellipsoid.Clarke_1880, -160, -6, -302);
		map.put("arc 1960 mean", Arc_1960_Mean);
		Ascension_Island_1958 = new Datum("Ascension Island 1958", "Ascension Island", Ellipsoid.International_1924,
				-205, 107, 53);
		map.put("ascension island 1958", Ascension_Island_1958);
		Astro_Beacon_E_1945 = new Datum("Astro Beacon E 1945", "Iwo Jima", Ellipsoid.International_1924, 145, 75, -272);
		map.put("astro beacon e 1945", Astro_Beacon_E_1945);
		Astro_DOS_714 = new Datum("Astro DOS 714", "St Helena Island", Ellipsoid.International_1924, -320, 550, -494);
		map.put("astro dos 714", Astro_DOS_714);
		Astro_Tern_Island_1961 = new Datum("Astro Tern Island 1961", "Tern Island", Ellipsoid.International_1924, 114,
				-116, -333);
		map.put("astro tern island 1961", Astro_Tern_Island_1961);
		Astronomical_Station_1952 = new Datum("Astronomical Station 1952", "Marcus Island",
				Ellipsoid.International_1924, 124, -234, -25);
		map.put("astronomical station 1952", Astronomical_Station_1952);
		Australian_Geodetic_1966 = new Datum("Australian Geodetic 1966", "Australia, Tasmania",
				Ellipsoid.Australian_National, -133, -48, 148);
		map.put("australian geodetic 1966", Australian_Geodetic_1966);
		Australian_Geodetic_1984 = new Datum("Australian Geodetic 1984", "Australia, Tasmania",
				Ellipsoid.Australian_National, -134, -48, 149);
		map.put("australian geodetic 1984", Australian_Geodetic_1984);
		Ayabelle_Lighthouse = new Datum("Ayabelle Lighthouse", "Djibouti", Ellipsoid.Clarke_1880, -79, -129, 145);
		map.put("ayabelle lighthouse", Ayabelle_Lighthouse);
		Bellevue = new Datum("Bellevue", "Efate and Erromango Islands", Ellipsoid.International_1924, -127, -769, 472);
		map.put("bellevue", Bellevue);
		Bermuda_1957 = new Datum("Bermuda 1957", "Bermuda", Ellipsoid.Clarke_1866, -73, 213, 296);
		map.put("bermuda 1957", Bermuda_1957);
		Bissau = new Datum("Bissau", "Guinea-Bissau", Ellipsoid.International_1924, -173, 253, 27);
		map.put("bissau", Bissau);
		Bogota_Observatory = new Datum("Bogota Observatory", "Colombia", Ellipsoid.International_1924, 307, 304, -318);
		map.put("bogota observatory", Bogota_Observatory);
		Bukit_Rimpah = new Datum("Bukit Rimpah", "Indonesia (Bangka and Belitung Ids)", Ellipsoid.Bessel_1841, -384,
				664, -48);
		map.put("bukit rimpah", Bukit_Rimpah);
		Camp_Area_Astro = new Datum("Camp Area Astro", "Antarctica (McMurdo Camp Area)", Ellipsoid.International_1924,
				-104, -129, 239);
		map.put("camp area astro", Camp_Area_Astro);
		Campo_Inchauspe = new Datum("Campo Inchauspe", "Argentina", Ellipsoid.International_1924, -148, 136, 90);
		map.put("campo inchauspe", Campo_Inchauspe);
		Canton_Astro_1966 = new Datum("Canton Astro 1966", "Phoenix Islands", Ellipsoid.International_1924, 298, -304,
				-375);
		map.put("canton astro 1966", Canton_Astro_1966);
		Cape = new Datum("Cape", "South Africa", Ellipsoid.Clarke_1880, -136, -108, -292);
		map.put("cape", Cape);
		Cape_Canaveral = new Datum("Cape Canaveral", "Bahamas, Florida", Ellipsoid.Clarke_1866, -2, 151, 181);
		map.put("cape canaveral", Cape_Canaveral);
		Carthage = new Datum("Carthage", "Tunisia", Ellipsoid.Clarke_1880, -263, 6, 431);
		map.put("carthage", Carthage);
		Chatham_Island_Astro_1971 = new Datum("Chatham Island Astro 1971", "New Zealand (Chatham Island)",
				Ellipsoid.International_1924, 175, -38, 113);
		map.put("chatham island astro 1971", Chatham_Island_Astro_1971);
		Chua_Astro = new Datum("Chua Astro", "Paraguay", Ellipsoid.International_1924, -134, 229, -29);
		map.put("chua astro", Chua_Astro);
		Corrego_Alegre = new Datum("Corrego Alegre", "Brazil", Ellipsoid.International_1924, -206, 172, -6);
		map.put("corrego alegre", Corrego_Alegre);
		DOS_1968 = new Datum("DOS 1968", "New Georgia Islands (Gizo Island)", Ellipsoid.International_1924, 230, -199,
				-752);
		map.put("dos 1968", DOS_1968);
		Dabola = new Datum("Dabola", "Guinea", Ellipsoid.Clarke_1880, -83, 37, 124);
		map.put("dabola", Dabola);
		Deception_Island = new Datum("Deception Island", "Deception Island, Antarctia", Ellipsoid.Clarke_1880, 260, 12,
				-147);
		map.put("deception island", Deception_Island);
		Djakarta_Batavia = new Datum("Djakarta Batavia", "Indonesia (Sumatra)", Ellipsoid.Bessel_1841, -377, 681, -50);
		map.put("djakarta batavia", Djakarta_Batavia);
		Easter_Island_1967 = new Datum("Easter Island 1967", "Easter Island", Ellipsoid.International_1924, 211, 147,
				111);
		map.put("easter island 1967", Easter_Island_1967);
		European_1950_Cyprus = new Datum("European 1950 Cyprus", "Cyprus", Ellipsoid.International_1924, -104, -101,
				-140);
		map.put("european 1950 cyprus", European_1950_Cyprus);
		European_1950_Egypt = new Datum("European 1950 Egypt", "Egypt", Ellipsoid.International_1924, -130, -117, -151);
		map.put("european 1950 egypt", European_1950_Egypt);
		European_1950_England = new Datum("European 1950 England", "England, Ireland, Scotland, Shetland Islands",
				Ellipsoid.International_1924, -86, -96, -120);
		map.put("european 1950 england", European_1950_England);
		European_1950_England_Channel = new Datum("European 1950 England Channel",
				"England, Channel Islands, Scotland, Shetland Islands", Ellipsoid.International_1924, -86, -96, -120);
		map.put("european 1950 england channel", European_1950_England_Channel);
		European_1950_Finland_Norway = new Datum("European 1950 Finland Norway", "Finland, Norway",
				Ellipsoid.International_1924, -87, -95, -120);
		map.put("european 1950 finland norway", European_1950_Finland_Norway);
		European_1950_Greece = new Datum("European 1950 Greece", "Greece", Ellipsoid.International_1924, -84, -95, -130);
		map.put("european 1950 greece", European_1950_Greece);
		European_1950_Iran = new Datum("European 1950 Iran", "Iran", Ellipsoid.International_1924, -117, -132, -164);
		map.put("european 1950 iran", European_1950_Iran);
		European_1950_Italy_Sardinia = new Datum("European 1950 Italy Sardinia", "Italy (Sardinia)",
				Ellipsoid.International_1924, -97, -103, -120);
		map.put("european 1950 italy sardinia", European_1950_Italy_Sardinia);
		European_1950_Italy_Sicily = new Datum("European 1950 Italy Sicily", "Italy (Sicily)",
				Ellipsoid.International_1924, -97, -88, -135);
		map.put("european 1950 italy sicily", European_1950_Italy_Sicily);
		European_1950_Malta = new Datum("European 1950 Malta", "Malta", Ellipsoid.International_1924, -107, -88, -149);
		map.put("european 1950 malta", European_1950_Malta);
		European_1950_Mean_Europe = new Datum(
				"European 1950 Mean Europe",
				"Mean for Austria, Belgium, Denmark, Finland, France, W Germany, Gibralter, Greece, Italy, Luxembourg, Netherlands, Norway, Portugal, Spain, Sweden, Switzerland",
				Ellipsoid.International_1924, -87, -98, -121);
		map.put("european 1950 mean europe", European_1950_Mean_Europe);
		European_1950_Middle_East = new Datum("European 1950 Middle East",
				"Mean for Iraq, Israel, Jordan, Lebanon, Kuwait, Saudi Arabia, Syria", Ellipsoid.International_1924,
				-103, -106, -141);
		map.put("european 1950 middle east", European_1950_Middle_East);
		European_1950_North_West_Europe = new Datum("European 1950 North West Europe",
				"Mean for Austria, Denmark, France, W Germany, Netherlands, Switzerland", Ellipsoid.International_1924,
				-87, -96, -120);
		map.put("european 1950 north west europe", European_1950_North_West_Europe);
		European_1950_Protugal_Spain = new Datum("European 1950 Protugal Spain", "Portugal, Spain",
				Ellipsoid.International_1924, -84, -107, -120);
		map.put("european 1950 protugal spain", European_1950_Protugal_Spain);
		European_1950_Tunisia = new Datum("European 1950 Tunisia", "Tunisia", Ellipsoid.International_1924, -112, -77,
				-145);
		map.put("european 1950 tunisia", European_1950_Tunisia);
		European_1979_Mean = new Datum("European 1979 Mean",
				"Mean for Austria, Finland, Netherlands, Norway, Spain, Sweden, Switzerland",
				Ellipsoid.International_1924, -86, -98, -119);
		map.put("european 1979 mean", European_1979_Mean);
		Fort_Thomas_1955 = new Datum("Fort Thomas 1955", "Nevis, St. Kitts (Leeward Islands)", Ellipsoid.Clarke_1880,
				-7, 215, 225);
		map.put("fort thomas 1955", Fort_Thomas_1955);
		GUX_1_Astro = new Datum("GUX 1 Astro", "Guadalcanal Island", Ellipsoid.International_1924, 252, -209, -751);
		map.put("gux 1 astro", GUX_1_Astro);
		Gan_1970 = new Datum("Gan 1970", "Republic of Maldives", Ellipsoid.International_1924, -133, -321, 50);
		map.put("gan 1970", Gan_1970);
		Geodetic_Datum_1949 = new Datum("Geodetic Datum 1949", "New Zealand", Ellipsoid.International_1924, 84, -22,
				209);
		map.put("geodetic datum 1949", Geodetic_Datum_1949);
		Guam_1963 = new Datum("Guam 1963", "Guam", Ellipsoid.Clarke_1866, -100, -248, 259);
		map.put("guam 1963", Guam_1963);
		Gunung_Segara = new Datum("Gunung Segara", "Indonesia (Kalimantan)", Ellipsoid.Bessel_1841, -403, 684, 41);
		map.put("gunung segara", Gunung_Segara);
		Herat_North = new Datum("Herat North", "Afghanistan", Ellipsoid.International_1924, -333, -222, 114);
		map.put("herat north", Herat_North);
		Hjorsey_1955 = new Datum("Hjorsey 1955", "Iceland", Ellipsoid.International_1924, -73, 46, -86);
		map.put("hjorsey 1955", Hjorsey_1955);
		Hong_Kong_1963 = new Datum("Hong Kong 1963", "Hong Kong", Ellipsoid.International_1924, -156, -271, -189);
		map.put("hong kong 1963", Hong_Kong_1963);
		Hu_Tzu_Shan = new Datum("Hu Tzu Shan", "Taiwan", Ellipsoid.International_1924, -637, -549, -203);
		map.put("hu tzu shan", Hu_Tzu_Shan);
		ISTS_061_Astro_1968 = new Datum("ISTS 061 Astro 1968", "South Georgia Islands", Ellipsoid.International_1924,
				-794, 119, -298);
		map.put("ists 061 astro 1968", ISTS_061_Astro_1968);
		ISTS_073_Astro_1969 = new Datum("ISTS 073 Astro 1969", "Diego Garcia", Ellipsoid.International_1924, 208, -435,
				-229);
		map.put("ists 073 astro 1969", ISTS_073_Astro_1969);
		Indian_Bangladesh = new Datum("Indian Bangladesh", "Bangladesh", Ellipsoid.Everest_India_1830, 282, 726, 254);
		map.put("indian bangladesh", Indian_Bangladesh);
		Indian_India_Nepal = new Datum("Indian India Nepal", "India, Nepal", Ellipsoid.Everest_India_1956, 295, 736,
				257);
		map.put("indian india nepal", Indian_India_Nepal);
		Indian_Pakistan = new Datum("Indian Pakistan", "Pakistan", Ellipsoid.Everest_Pakistan, 283, 682, 231);
		map.put("indian pakistan", Indian_Pakistan);
		Indian_1954 = new Datum("Indian 1954", "Thailand", Ellipsoid.Everest_India_1830, 217, 823, 299);
		map.put("indian 1954", Indian_1954);
		Indian_1960_Vietnam_Cons_Son = new Datum("Indian 1960 Vietnam Cons Son", "Vietnam (Con Son Island)",
				Ellipsoid.Everest_India_1830, 182, 915, 344);
		map.put("indian 1960 vietnam cons son", Indian_1960_Vietnam_Cons_Son);
		Indian_1960_Vietnam_Near_16_N = new Datum("Indian 1960 Vietnam Near 16 N", "Vietnam (Near 16øN)",
				Ellipsoid.Everest_India_1830, 198, 881, 317);
		map.put("indian 1960 vietnam near 16 n", Indian_1960_Vietnam_Near_16_N);
		Indian_1975 = new Datum("Indian 1975", "Thailand", Ellipsoid.Everest_India_1830, 209, 818, 290);
		map.put("indian 1975", Indian_1975);
		Indonesian_1974 = new Datum("Indonesian 1974", "Indonesia", Ellipsoid.Indonesian_1974, -24, -15, 5);
		map.put("indonesian 1974", Indonesian_1974);
		Ireland_1965 = new Datum("Ireland 1965", "Ireland", Ellipsoid.Modified_Airy, 506, -122, 611);
		map.put("ireland 1965", Ireland_1965);
		Johnston_Island_1961 = new Datum("Johnston Island 1961", "Johnston Island", Ellipsoid.International_1924, 189,
				-79, -202);
		map.put("johnston island 1961", Johnston_Island_1961);
		Kandawala = new Datum("Kandawala", "Sri Lanka", Ellipsoid.Everest_India_1830, -97, 787, 86);
		map.put("kandawala", Kandawala);
		Kerguelen_Island_1949 = new Datum("Kerguelen Island 1949", "Kerguelen Island", Ellipsoid.International_1924,
				145, -187, 103);
		map.put("kerguelen island 1949", Kerguelen_Island_1949);
		Kertau_1948 = new Datum("Kertau 1948", "West Malaysia and Singapore",
				Ellipsoid.Everest_Malay_and_Singapore_1948, -11, 851, 5);
		map.put("kertau 1948", Kertau_1948);
		Kusaie_Astro_1951 = new Datum("Kusaie Astro 1951", "Caroline Islands", Ellipsoid.International_1924, 647, 1777,
				-1124);
		map.put("kusaie astro 1951", Kusaie_Astro_1951);
		L_C_5_Astro_1961 = new Datum("L C 5 Astro 1961", "Cayman Brac Island", Ellipsoid.Clarke_1866, 42, 124, 147);
		map.put("l c 5 astro 1961", L_C_5_Astro_1961);
		Leigon = new Datum("Leigon", "Ghana", Ellipsoid.Clarke_1880, -130, 29, 364);
		map.put("leigon", Leigon);
		Liberia_1964 = new Datum("Liberia 1964", "Liberia", Ellipsoid.Clarke_1880, -90, 40, 88);
		map.put("liberia 1964", Liberia_1964);
		Luzon_Philippines = new Datum("Luzon Philippines", "Philippines (Excluding Mindanao)", Ellipsoid.Clarke_1866,
				-133, -77, -51);
		map.put("luzon philippines", Luzon_Philippines);
		Luzon_Philippines_Mindanao = new Datum("Luzon Philippines Mindanao", "Philippines (Mindanao)",
				Ellipsoid.Clarke_1866, -133, -79, -72);
		map.put("luzon philippines mindanao", Luzon_Philippines_Mindanao);
		MPoraloko = new Datum("MPoraloko", "Gabon", Ellipsoid.Clarke_1880, -74, -130, 42);
		map.put("mporaloko", MPoraloko);
		Mahe_1971 = new Datum("Mahe 1971", "Mahe Island", Ellipsoid.Clarke_1880, 41, -220, -134);
		map.put("mahe 1971", Mahe_1971);
		Massawa = new Datum("Massawa", "Ethiopia (Eritrea)", Ellipsoid.Bessel_1841, 639, 405, 60);
		map.put("massawa", Massawa);
		Merchich = new Datum("Merchich", "Morocco", Ellipsoid.Clarke_1880, 31, 146, 47);
		map.put("merchich", Merchich);
		Midway_Astro_1961 = new Datum("Midway Astro 1961", "Midway Islands", Ellipsoid.International_1924, 912, -58,
				1227);
		map.put("midway astro 1961", Midway_Astro_1961);
		Minna_Cameroon = new Datum("Minna Cameroon", "Cameroon", Ellipsoid.Clarke_1880, -81, -84, 115);
		map.put("minna cameroon", Minna_Cameroon);
		Minna_Nigeria = new Datum("Minna Nigeria", "Nigeria", Ellipsoid.Clarke_1880, -92, -93, 122);
		map.put("minna nigeria", Minna_Nigeria);
		Montserrat_Island_Astro_1958 = new Datum("Montserrat Island Astro 1958", "Montserrat (Leeward Islands)",
				Ellipsoid.Clarke_1880, 174, 359, 365);
		map.put("montserrat island astro 1958", Montserrat_Island_Astro_1958);
		NTF_Nouvelle_Triangulation_de_France = new Datum("NTF Nouvelle Triangulation de France",
				"France (incl. Corsica)", Ellipsoid.Clarke_1880, -168, -60, 320);
		map.put("ntf nouvelle triangulation de france", NTF_Nouvelle_Triangulation_de_France);
		Nahrwan_Oman = new Datum("Nahrwan Oman", "Oman (Masirah Island)", Ellipsoid.Clarke_1880, -247, -148, 369);
		map.put("nahrwan oman", Nahrwan_Oman);
		Nahrwan_Saudi_Arabia = new Datum("Nahrwan Saudi Arabia", "Saudi Arabia", Ellipsoid.Clarke_1880, -243, -192, 477);
		map.put("nahrwan saudi arabia", Nahrwan_Saudi_Arabia);
		Nahrwan_United_Arab_Emirates = new Datum("Nahrwan United Arab Emirates", "United Arab Emirates",
				Ellipsoid.Clarke_1880, -249, -156, 381);
		map.put("nahrwan united arab emirates", Nahrwan_United_Arab_Emirates);
		Naparima_BWI = new Datum("Naparima BWI", "Trinidad and Tobago", Ellipsoid.International_1924, -10, 375, 165);
		map.put("naparima bwi", Naparima_BWI);
		North_American_1927_Alaska = new Datum("North American 1927 Alaska", "Alaska (Excluding Aleutian Ids)",
				Ellipsoid.Clarke_1866, -5, 135, 172);
		map.put("north american 1927 alaska", North_American_1927_Alaska);
		North_American_1927_Alaska_Aleutian_East = new Datum("North American 1927 Alaska Aleutian East",
				"Alaska (Aleutian Ids East of 180øW)", Ellipsoid.Clarke_1866, -2, 152, 149);
		map.put("north american 1927 alaska aleutian east", North_American_1927_Alaska_Aleutian_East);
		North_American_1927_Alaska_Aleutian_West = new Datum("North American 1927 Alaska Aleutian West",
				"Alaska (Aleutian Ids West of 180øW)", Ellipsoid.Clarke_1866, 2, 204, 105);
		map.put("north american 1927 alaska aleutian west", North_American_1927_Alaska_Aleutian_West);
		North_American_1927_Bahamas = new Datum("North American 1927 Bahamas", "Bahamas (Except San Salvador Id)",
				Ellipsoid.Clarke_1866, -4, 154, 178);
		map.put("north american 1927 bahamas", North_American_1927_Bahamas);
		North_American_1927_Bahamas_San_Salvador = new Datum("North American 1927 Bahamas San Salvador",
				"Bahamas (San Salvador Island)", Ellipsoid.Clarke_1866, 1, 140, 165);
		map.put("north american 1927 bahamas san salvador", North_American_1927_Bahamas_San_Salvador);
		North_American_1927_Canada = new Datum("North American 1927 Canada", "Mean for Canada", Ellipsoid.Clarke_1866,
				-10, 158, 187);
		map.put("north american 1927 canada", North_American_1927_Canada);
		North_American_1927_Canada_East = new Datum("North American 1927 Canada East",
				"Canada (New Brunswick, Newfoundland, Nova Scotia, Quebec)", Ellipsoid.Clarke_1866, -22, 160, 190);
		map.put("north american 1927 canada east", North_American_1927_Canada_East);
		North_American_1927_Canada_Middle = new Datum("North American 1927 Canada Middle",
				"Canada (Manitoba, Ontario)", Ellipsoid.Clarke_1866, -9, 157, 184);
		map.put("north american 1927 canada middle", North_American_1927_Canada_Middle);
		North_American_1927_Canada_North = new Datum("North American 1927 Canada North",
				"Canada (Northwest Territories, Saskatchewan)", Ellipsoid.Clarke_1866, 4, 159, 188);
		map.put("north american 1927 canada north", North_American_1927_Canada_North);
		North_American_1927_Canada_West = new Datum("North American 1927 Canada West",
				"Canada (Alberta, British Columbia)", Ellipsoid.Clarke_1866, -7, 162, 188);
		map.put("north american 1927 canada west", North_American_1927_Canada_West);
		North_American_1927_Canada_Yukon = new Datum("North American 1927 Canada Yukon", "Canada (Yukon)",
				Ellipsoid.Clarke_1866, -7, 139, 181);
		map.put("north american 1927 canada yukon", North_American_1927_Canada_Yukon);
		North_American_1927_Canal_Zone = new Datum("North American 1927 Canal Zone", "Canal Zone",
				Ellipsoid.Clarke_1866, 0, 125, 201);
		map.put("north american 1927 canal zone", North_American_1927_Canal_Zone);
		North_American_1927_Caribean = new Datum(
				"North American 1927 Caribean",
				"Mean for Antigua, Barbados, Barbuda, Caicos Islands, Cuba, Dominican Republic, Grand Cayman, Jamaica, Turks Islands",
				Ellipsoid.Clarke_1866, -3, 142, 183);
		map.put("north american 1927 caribean", North_American_1927_Caribean);
		North_American_1927_Central_America = new Datum("North American 1927 Central America",
				"Mean for Belize, Costa Rica, El Salvador, Guatemala, Honduras, Nicaragua", Ellipsoid.Clarke_1866, 0,
				125, 194);
		map.put("north american 1927 central america", North_American_1927_Central_America);
		North_American_1927_Conus = new Datum("North American 1927 Conus", "Mean for CONUS", Ellipsoid.Clarke_1866, -8,
				160, 176);
		map.put("north american 1927 conus", North_American_1927_Conus);
		North_American_1927_Conus_East = new Datum("North American 1927 Conus East",
				"Mean for CONUS (East of Mississippi River Including Louisiana, Missouri, Minnesota)",
				Ellipsoid.Clarke_1866, -9, 161, 179);
		map.put("north american 1927 conus east", North_American_1927_Conus_East);
		North_American_1927_Conus_West = new Datum("North American 1927 Conus West",
				"Mean for CONUS (West of Mississippi River Excluding Louisiana, Minnesota, Missouri)",
				Ellipsoid.Clarke_1866, -8, 159, 175);
		map.put("north american 1927 conus west", North_American_1927_Conus_West);
		North_American_1927_Cuba = new Datum("North American 1927 Cuba", "Cuba", Ellipsoid.Clarke_1866, -9, 152, 178);
		map.put("north american 1927 cuba", North_American_1927_Cuba);
		North_American_1927_Greenland = new Datum("North American 1927 Greenland", "Greenland (Hayes Peninsula)",
				Ellipsoid.Clarke_1866, 11, 114, 195);
		map.put("north american 1927 greenland", North_American_1927_Greenland);
		North_American_1927_Mexico = new Datum("North American 1927 Mexico", "Mexico", Ellipsoid.Clarke_1866, -12, 130,
				190);
		map.put("north american 1927 mexico", North_American_1927_Mexico);
		North_American_1983_Alaska = new Datum("North American 1983 Alaska", "Alaska (Excluding Aleutian Ids)",
				Ellipsoid.GRS_1980, 0, 0, 0);
		map.put("north american 1983 alaska", North_American_1983_Alaska);
		North_American_1983_Alaska_Aleutian = new Datum("North American 1983 Alaska Aleutian", "Aleutian Ids",
				Ellipsoid.GRS_1980, -2, 0, 4);
		map.put("north american 1983 alaska aleutian", North_American_1983_Alaska_Aleutian);
		North_American_1983_Canada = new Datum("North American 1983 Canada", "Canada", Ellipsoid.GRS_1980, 0, 0, 0);
		map.put("north american 1983 canada", North_American_1983_Canada);
		North_American_1983_Central_America = new Datum("North American 1983 Central America", "Central America",
				Ellipsoid.GRS_1980, 0, 0, 0);
		map.put("north american 1983 central america", North_American_1983_Central_America);
		North_American_1983_Conus = new Datum("North American 1983 Conus", "Conus", Ellipsoid.GRS_1980, 0, 0, 0);
		map.put("north american 1983 conus", North_American_1983_Conus);
		North_American_1983_Hawaii = new Datum("North American 1983 Hawaii", "Hawaii", Ellipsoid.GRS_1980, 1, 1, -1);
		map.put("north american 1983 hawaii", North_American_1983_Hawaii);
		North_American_1983_Mexico = new Datum("North American 1983 Mexico", "Mexico", Ellipsoid.GRS_1980, 0, 0, 0);
		map.put("north american 1983 mexico", North_American_1983_Mexico);
		North_Sahara_1959 = new Datum("North Sahara 1959", "Algeria", Ellipsoid.Clarke_1880, -186, -93, 310);
		map.put("north sahara 1959", North_Sahara_1959);
		Observatorio_Meteorologico_1939 = new Datum("Observatorio Meteorologico 1939",
				"Azores (Corvo and Flores Islands)", Ellipsoid.International_1924, -425, -169, 81);
		map.put("observatorio meteorologico 1939", Observatorio_Meteorologico_1939);
		Old_Egyptian_1907 = new Datum("Old Egyptian 1907", "Egypt", Ellipsoid.Helmert_1906, -130, 110, -13);
		map.put("old egyptian 1907", Old_Egyptian_1907);
		Old_Hawaiian_Hawaii = new Datum("Old Hawaiian Hawaii", "Hawaii", Ellipsoid.Clarke_1866, 89, -279, -183);
		map.put("old hawaiian hawaii", Old_Hawaiian_Hawaii);
		Old_Hawaiian_Kauai = new Datum("Old Hawaiian Kauai", "Kauai", Ellipsoid.Clarke_1866, 45, -290, -172);
		map.put("old hawaiian kauai", Old_Hawaiian_Kauai);
		Old_Hawaiian_Maui = new Datum("Old Hawaiian Maui", "Maui", Ellipsoid.Clarke_1866, 65, -290, -190);
		map.put("old hawaiian maui", Old_Hawaiian_Maui);
		Old_Hawaiian_Mean = new Datum("Old Hawaiian Mean", "Mean for Hawaii, Kauai, Maui, Oahu", Ellipsoid.Clarke_1866,
				61, -285, -181);
		map.put("old hawaiian mean", Old_Hawaiian_Mean);
		Old_Hawaiian_Oahu = new Datum("Old Hawaiian Oahu", "Oahu", Ellipsoid.Clarke_1866, 58, -283, -182);
		map.put("old hawaiian oahu", Old_Hawaiian_Oahu);
		Oman = new Datum("Oman", "Oman", Ellipsoid.Clarke_1880, -346, -1, 224);
		map.put("oman", Oman);
		Ordnance_Survey_Great_Britain_1936_England = new Datum("Ordnance Survey Great Britain 1936 England", "England",
				Ellipsoid.Airy_1830, 371, -112, 434);
		map.put("ordnance survey great britain 1936 england", Ordnance_Survey_Great_Britain_1936_England);
		Ordnance_Survey_Great_Britain_1936_England_Wales = new Datum(
				"Ordnance Survey Great Britain 1936 England Wales", "England, Isle of Man, Wales", Ellipsoid.Airy_1830,
				371, -111, 434);
		map.put("ordnance survey great britain 1936 england wales", Ordnance_Survey_Great_Britain_1936_England_Wales);
		Ordnance_Survey_Great_Britain_1936_Mean = new Datum("Ordnance Survey Great Britain 1936 Mean",
				"Mean for England, Isle of Man, Scotland, Shetland Islands, Wales", Ellipsoid.Airy_1830, 375, -111, 431);
		map.put("ordnance survey great britain 1936 mean", Ordnance_Survey_Great_Britain_1936_Mean);
		Ordnance_Survey_Great_Britain_1936_Scotland = new Datum("Ordnance Survey Great Britain 1936 Scotland",
				"Scotland, Shetland Islands", Ellipsoid.Airy_1830, 384, -111, 425);
		map.put("ordnance survey great britain 1936 scotland", Ordnance_Survey_Great_Britain_1936_Scotland);
		Ordnance_Survey_Great_Britain_1936_Wales = new Datum("Ordnance Survey Great Britain 1936 Wales", "Wales",
				Ellipsoid.Airy_1830, 370, -108, 434);
		map.put("ordnance survey great britain 1936 wales", Ordnance_Survey_Great_Britain_1936_Wales);
		Pico_de_las_Nieves = new Datum("Pico de las Nieves", "Canary Islands", Ellipsoid.International_1924, -307, -92,
				127);
		map.put("pico de las nieves", Pico_de_las_Nieves);
		Pitcairn_Astro_1967 = new Datum("Pitcairn Astro 1967", "Pitcairn Island", Ellipsoid.International_1924, 185,
				165, 42);
		map.put("pitcairn astro 1967", Pitcairn_Astro_1967);
		Point_58 = new Datum("Point 58", "Mean for Burkina Faso and Niger", Ellipsoid.Clarke_1880, -106, -129, 165);
		map.put("point 58", Point_58);
		Pointe_Noire_1948 = new Datum("Pointe Noire 1948", "Congo", Ellipsoid.Clarke_1880, -148, 51, -291);
		map.put("pointe noire 1948", Pointe_Noire_1948);
		Porto_Santo_1936 = new Datum("Porto Santo 1936", "Porto Santo, Madeira Islands", Ellipsoid.International_1924,
				-499, -249, 314);
		map.put("porto santo 1936", Porto_Santo_1936);
		Provisional_South_American_1956_Bolivia = new Datum("Provisional South American 1956 Bolivia", "Bolivia",
				Ellipsoid.International_1924, -270, 188, -388);
		map.put("provisional south american 1956 bolivia", Provisional_South_American_1956_Bolivia);
		Provisional_South_American_1956_Chile_North = new Datum("Provisional South American 1956 Chile North",
				"Chile (Northern, Near 19øS)", Ellipsoid.International_1924, -270, 183, -390);
		map.put("provisional south american 1956 chile north", Provisional_South_American_1956_Chile_North);
		Provisional_South_American_1956_Chile_South = new Datum("Provisional South American 1956 Chile South",
				"Chile (Southern, Near 43øS)", Ellipsoid.International_1924, -305, 243, -442);
		map.put("provisional south american 1956 chile south", Provisional_South_American_1956_Chile_South);
		Provisional_South_American_1956_Colombia = new Datum("Provisional South American 1956 Colombia", "Colombia",
				Ellipsoid.International_1924, -282, 169, -371);
		map.put("provisional south american 1956 colombia", Provisional_South_American_1956_Colombia);
		Provisional_South_American_1956_Ecuador = new Datum("Provisional South American 1956 Ecuador", "Ecuador",
				Ellipsoid.International_1924, -278, 171, -367);
		map.put("provisional south american 1956 ecuador", Provisional_South_American_1956_Ecuador);
		Provisional_South_American_1956_Guyana = new Datum("Provisional South American 1956 Guyana", "Guyana",
				Ellipsoid.International_1924, -298, 159, -369);
		map.put("provisional south american 1956 guyana", Provisional_South_American_1956_Guyana);
		Provisional_South_American_1956_Mean = new Datum("Provisional South American 1956 Mean",
				"Mean for Bolivia, Chile, Colombia, Ecuador, Guyana, Peru, Venezuela", Ellipsoid.International_1924,
				-288, 175, -376);
		map.put("provisional south american 1956 mean", Provisional_South_American_1956_Mean);
		Provisional_South_American_1956_Peru = new Datum("Provisional South American 1956 Peru", "Peru",
				Ellipsoid.International_1924, -279, 175, -379);
		map.put("provisional south american 1956 peru", Provisional_South_American_1956_Peru);
		Provisional_South_American_1956_Venezuela = new Datum("Provisional South American 1956 Venezuela", "Venezuela",
				Ellipsoid.International_1924, -295, 173, -371);
		map.put("provisional south american 1956 venezuela", Provisional_South_American_1956_Venezuela);
		Provisional_South_Chilean_1963 = new Datum("Provisional South Chilean 1963", "Chile (Near 53øS) (Hito XVIII)",
				Ellipsoid.International_1924, 16, 196, 93);
		map.put("provisional south chilean 1963", Provisional_South_Chilean_1963);
		Puerto_Rico = new Datum("Puerto Rico", "Puerto Rico, Virgin Islands", Ellipsoid.Clarke_1866, 11, 72, -101);
		map.put("puerto rico", Puerto_Rico);
		Pulkovo_1942 = new Datum("Pulkovo 1942", "Russia", Ellipsoid.Krassovsky_1940, 28, -130, -95);
		map.put("pulkovo 1942", Pulkovo_1942);
		Qatar_National = new Datum("Qatar National", "Qatar", Ellipsoid.International_1924, -128, -283, 22);
		map.put("qatar national", Qatar_National);
		Qornoq = new Datum("Qornoq", "Greenland (South)", Ellipsoid.International_1924, 164, 138, -189);
		map.put("qornoq", Qornoq);
		Reunion = new Datum("Reunion", "Mascarene Islands", Ellipsoid.International_1924, 94, -948, -1262);
		map.put("reunion", Reunion);
		Rijks_Driehoeksmeting = new Datum("Rijks Driehoeksmeting", "Netherlands", Ellipsoid.Bessel_1841, -593, -26,
				-478);
		map.put("rijks driehoeksmeting", Rijks_Driehoeksmeting);
		Rome_1940 = new Datum("Rome 1940", "Italy (Sardinia)", Ellipsoid.International_1924, -225, -65, 9);
		map.put("rome 1940", Rome_1940);
		S_42_Pulkovo_1942 = new Datum("S 42 Pulkovo 1942", "Hungary", Ellipsoid.Krassovsky_1940, 28, -121, -77);
		map.put("s 42 pulkovo 1942", S_42_Pulkovo_1942);
		S_JTSK = new Datum("S JTSK", "Czechoslavakia (Prior 1 JAN 1993)", Ellipsoid.Bessel_1841, 589, 76, 480);
		map.put("s jtsk", S_JTSK);
		Santo_DOS_1965 = new Datum("Santo DOS 1965", "Espirito Santo Island", Ellipsoid.International_1924, 170, 42, 84);
		map.put("santo dos 1965", Santo_DOS_1965);
		Sao_Braz = new Datum("Sao Braz", "Azores (Sao Miguel, Santa Maria Ids)", Ellipsoid.International_1924, -203,
				141, 53);
		map.put("sao braz", Sao_Braz);
		Sapper_Hill_1943 = new Datum("Sapper Hill 1943", "East Falkland Island", Ellipsoid.International_1924, -355,
				21, 72);
		map.put("sapper hill 1943", Sapper_Hill_1943);
		Schwarzeck = new Datum("Schwarzeck", "Namibia", Ellipsoid.Bessel_1841_Namibia, 616, 97, -251);
		map.put("schwarzeck", Schwarzeck);
		Selvagem_Grande_1938 = new Datum("Selvagem Grande 1938", "Salvage Islands", Ellipsoid.International_1924, -289,
				-124, 60);
		map.put("selvagem grande 1938", Selvagem_Grande_1938);
		South_American_1969_Argentina = new Datum("South American 1969 Argentina", "Argentina",
				Ellipsoid.South_American_1969, -62, -1, -37);
		map.put("south american 1969 argentina", South_American_1969_Argentina);
		South_American_1969_Bolivia = new Datum("South American 1969 Bolivia", "Bolivia",
				Ellipsoid.South_American_1969, -61, 2, -48);
		map.put("south american 1969 bolivia", South_American_1969_Bolivia);
		South_American_1969_Brazil = new Datum("South American 1969 Brazil", "Brazil", Ellipsoid.South_American_1969,
				-60, -2, -41);
		map.put("south american 1969 brazil", South_American_1969_Brazil);
		South_American_1969_Chile = new Datum("South American 1969 Chile", "Chile", Ellipsoid.South_American_1969, -75,
				-1, -44);
		map.put("south american 1969 chile", South_American_1969_Chile);
		South_American_1969_Colombia = new Datum("South American 1969 Colombia", "Colombia",
				Ellipsoid.South_American_1969, -44, 6, -36);
		map.put("south american 1969 colombia", South_American_1969_Colombia);
		South_American_1969_Ecuador = new Datum("South American 1969 Ecuador", "Ecuador",
				Ellipsoid.South_American_1969, -48, 3, -44);
		map.put("south american 1969 ecuador", South_American_1969_Ecuador);
		South_American_1969_Ecuador_Baltra = new Datum("South American 1969 Ecuador Baltra",
				"Ecuador (Baltra, Galapagos)", Ellipsoid.South_American_1969, -47, 26, -4);
		map.put("south american 1969 ecuador baltra", South_American_1969_Ecuador_Baltra);
		South_American_1969_Guyana = new Datum("South American 1969 Guyana", "Guyana", Ellipsoid.South_American_1969,
				-53, 3, -47);
		map.put("south american 1969 guyana", South_American_1969_Guyana);
		South_American_1969_Mean = new Datum(
				"South American 1969 Mean",
				"Mean for Argentina, Bolivia, Brazil, Chile, Colombia, Ecuador, Guyana, Paraguay, Peru, Trinidad and Tobago, Venezuela",
				Ellipsoid.South_American_1969, -57, 1, -41);
		map.put("south american 1969 mean", South_American_1969_Mean);
		South_American_1969_Paraguay = new Datum("South American 1969 Paraguay", "Paraguay",
				Ellipsoid.South_American_1969, -61, 2, -33);
		map.put("south american 1969 paraguay", South_American_1969_Paraguay);
		South_American_1969_Peru = new Datum("South American 1969 Peru", "Peru", Ellipsoid.South_American_1969, -58, 0,
				-44);
		map.put("south american 1969 peru", South_American_1969_Peru);
		South_American_1969_Trinidad_and_Tobago = new Datum("South American 1969 Trinidad and Tobago",
				"Trinidad and Tobago", Ellipsoid.South_American_1969, -45, 12, -33);
		map.put("south american 1969 trinidad and tobago", South_American_1969_Trinidad_and_Tobago);
		South_American_1969_Venezuala = new Datum("South American 1969 Venezuala", "Venezuala",
				Ellipsoid.South_American_1969, -45, 8, -33);
		map.put("south american 1969 venezuala", South_American_1969_Venezuala);
		South_Asia = new Datum("South Asia", "Singapore", Ellipsoid.Modified_Fischer_1960, 7, -10, -26);
		map.put("south asia", South_Asia);
		Tananarive_Observatory_1925 = new Datum("Tananarive Observatory 1925", "Madagascar",
				Ellipsoid.International_1924, -189, -242, -91);
		map.put("tananarive observatory 1925", Tananarive_Observatory_1925);
		Timbalai_1948 = new Datum("Timbalai 1948", "Brunei, E. Malaysia (Sabah Sarawak)",
				Ellipsoid.Everest_Sabah_Sarawak, -679, 669, -48);
		map.put("timbalai 1948", Timbalai_1948);
		Tokyo_Japan = new Datum("Tokyo Japan", "Japan", Ellipsoid.Bessel_1841, -148, 507, 685);
		map.put("tokyo japan", Tokyo_Japan);
		Tokyo_Mean = new Datum("Tokyo Mean", "Mean for Japan, South Korea, Okinawa", Ellipsoid.Bessel_1841, -148, 507,
				685);
		map.put("tokyo mean", Tokyo_Mean);
		Tokyo_Okinawa = new Datum("Tokyo Okinawa", "Okinawa", Ellipsoid.Bessel_1841, -158, 507, 676);
		map.put("tokyo okinawa", Tokyo_Okinawa);
		Tokyo_South_Korea = new Datum("Tokyo South Korea", "South Korea", Ellipsoid.Bessel_1841, -146, 507, 687);
		map.put("tokyo south korea", Tokyo_South_Korea);
		Tristan_Astro_1968 = new Datum("Tristan Astro 1968", "Tristan da Cunha", Ellipsoid.International_1924, -632,
				438, -609);
		map.put("tristan astro 1968", Tristan_Astro_1968);
		Viti_Levu_1916 = new Datum("Viti Levu 1916", "Fiji (Viti Levu Island)", Ellipsoid.Clarke_1880, 51, 391, -36);
		map.put("viti levu 1916", Viti_Levu_1916);
		Voirol_1960 = new Datum("Voirol 1960", "Algeria", Ellipsoid.Clarke_1880, -123, -206, 219);
		map.put("voirol 1960", Voirol_1960);
		WGS_1984 = new Datum("WGS_1984", "Global Definition", Ellipsoid.WGS_1984, 0, 0, 0);
		map.put("wgs 1984", WGS_1984);
		Wake_Island_Astro_1952 = new Datum("Wake Island Astro 1952", "Wake Atoll", Ellipsoid.International_1924, 276,
				-57, 149);
		map.put("wake island astro 1952", Wake_Island_Astro_1952);
		Wake_Eniwetok_1960 = new Datum("Wake Eniwetok 1960", "Marshall Islands", Ellipsoid.Hough_1960, 102, 52, -38);
		map.put("wake eniwetok 1960", Wake_Eniwetok_1960);
		Yacare = new Datum("Yacare", "Uruguay", Ellipsoid.International_1924, -155, 171, 37);
		map.put("yacare", Yacare);
		Zanderij = new Datum("Zanderij", "Suriname", Ellipsoid.International_1924, -265, 120, -358);
		map.put("zanderij", Zanderij);
	}

	private final Ellipsoid		ellipsoid;
	private final String		name;
	private final double		dx, dy, dz;
	private final String		regionOfUse;
	private final double		ex, ey, ez;

	public Datum(Ellipsoid ellipsoid) {
		this("", "", ellipsoid, 0, 0, 0, 0, 0, 0);
	}

	public Datum(String name, Ellipsoid ellipsoid) {
		this(name, "", ellipsoid, 0, 0, 0, 0, 0, 0);
	}

	public Datum(String name, Ellipsoid ellipsoid, double dx, double dy, double dz) {
		this(name, "", ellipsoid, dx, dy, dz, 0, 0, 0);
	}

	public Datum(String name, String regionOfUse, Ellipsoid ellipsoid, double dx, double dy, double dz) {
		this(name, regionOfUse, ellipsoid, dx, dy, dz, 0, 0, 0);
	}

	public Datum(String name, String regionOfUse, Ellipsoid ellipsoid, double dx, double dy, double dz, double ex,
			double ey, double ez) {
		this.name = name;
		this.regionOfUse = regionOfUse;
		this.ellipsoid = ellipsoid;
		this.dx = dx;
		this.dy = dy;
		this.dz = dz;
		this.ex = ex;
		this.ey = ey;
		this.ez = ez;
	}

	public String toStringPRJ() {
		String nm = name;
		if (!nm.startsWith("D_")) {
			nm = "D_" + name;
		}
		return String.format("DATUM[\"%s\",%s]", nm, ellipsoid.toStringPRJ());
	}

	@Override
	public String toString() {
		return String.format(
				"DATUM[\"%s\", \"%s\",\n            %s,\n            %f, %f, %f,\n            %f, %f, %f]", name,
				regionOfUse, ellipsoid, dx, dy, dz, ex, ey, ez);
	}

	public Ellipsoid getEllipsoid() {
		return ellipsoid;
	}

	public String getName() {
		return name;
	}

	public String getRegionOfUse() {
		return regionOfUse;
	}

	public double getDx() {
		return dx;
	}

	public double getDy() {
		return dy;
	}

	public double getDz() {
		return dz;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof Datum) {
			Datum dat = (Datum) obj;
			if (!this.ellipsoid.equals(dat.ellipsoid)) {
				return false;
			}
			if (!this.name.equals(dat.name)) {
				return false;
			}
			if (!this.regionOfUse.equals(dat.regionOfUse)) {
				return false;
			}
			if (this.dx != dat.dx) {
				return false;
			}
			if (this.dy != dat.dy) {
				return false;
			}
			if (this.dz != dat.dz) {
				return false;
			}
			if (this.ex != dat.ex) {
				return false;
			}
			if (this.ey != dat.ey) {
				return false;
			}
			if (this.ez != dat.ez) {
				return false;
			}

			return true;
		}
		// TODO Auto-generated method stub
		return super.equals(obj);
	}
}
